apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-meme
  labels:
    app: random-meme
    app.openshift.io/runtime: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-meme
  template:
    metadata:
      labels:
        app: random-meme
    spec:
      containers:
      - name: random-meme
        image: quay.io/evanshortiss/random-meme:sha-da50318
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 8080
          protocol: TCP